package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "bg_customiser_cpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main",
        "//mediapipe/graphs/bg_customiser:desktop_live_calculators",
    ],
)
